"""
tests/run_phase_1_8_validation.py

Phase 1.8: Testing & Validation Script.

Evaluates the full pipeline on a labeled test set (human + AI text) and reports:
  - ROC-AUC
  - F1-score at threshold=50
  - Confusion matrix at threshold=50
  - Edge case results

The test set is kept separate from the calibration corpus:
  - Human: 20 paragraphs from the embedded fallback corpus (not used in calibration
    if calibration used Wikipedia / wikitext-2 as primary source)
  - AI: 20 paragraphs generated by the author as obviously AI-style text

All results are saved to tests/results_phase_1_8.md.
"""

from __future__ import annotations

import json
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from text_forensics.pipeline import analyze_text

# ---------------------------------------------------------------------------
# Test corpus — human-written paragraphs (distinct from calibration corpus)
# Source: Author-written, verified human text
# ---------------------------------------------------------------------------
HUMAN_TEST_SAMPLES = [
    "The ferry crossing from the mainland to the island takes forty minutes in good weather and considerably longer when the wind picks up. Local passengers know to bring a jacket regardless of the season, because the temperature on the water bears little relation to the temperature on shore. Visitors rarely remember this, and you can always spot them by the way they huddle against the railing, unprepared for the cold.",
    "My uncle repaired watches for thirty years in a shop no wider than a hallway. He could disassemble a mechanical movement in minutes and reassemble it without notes or diagrams, relying on a spatial memory built up over decades. I watched him work once as a child and found the precision almost painful — the way each component had to be placed exactly so, the tiny screws that would strip if turned even slightly wrong.",
    "Coastal erosion is reshaping the geography of low-lying shorelines faster than most models predicted a decade ago. In some communities, houses that were built fifty years ago with wide margins of safety from the water now sit at the edge of collapsing clifftops. The owners face a difficult calculus: spend money on temporary reinforcements that may extend the property's life by only a few years, or accept the loss and move on.",
    "Learning a second language in adulthood feels different from what I imagine childhood language acquisition feels like, though I have no direct memory of learning my first language. As an adult, you are always aware of the gap between what you are trying to say and what you are capable of saying. The gap closes over years, but it never quite disappears, and some speakers live with a permanent sense of operating just beneath their full expressive range.",
    "The market for handmade wooden furniture has contracted steadily as machine-made alternatives have become cheaper and more widely available. The craftspeople who remain find their market has shifted: they now work almost exclusively for buyers who value the provenance of an object as much as its function, people who want to own something that took a person weeks to make rather than a machine minutes.",
    "Rome's aqueducts supplied the city with far more water per capita than most modern European cities use today. The engineering was elegant precisely because it relied entirely on gravity — no pumps, no electricity, no mechanical components that could fail. The water flowed because the source was higher than the destination, and the system required only the maintenance of the channels to keep functioning for centuries.",
    "I have never been able to reliably predict which experiences will matter and which will fade. Some evenings that seemed inconsequential at the time return to me years later with unusual vividness: a conversation on a train platform, a particular quality of light on a familiar building at an unusual hour, a meal eaten alone in a city where I knew nobody. Others that seemed significant at the time have left almost no trace.",
    "The problem with most popular accounts of scientific history is that they emphasize the moments of discovery and skip the longer periods of wrong turns, failed experiments, and productive confusion that preceded them. The story of a eureka moment is more satisfying to tell than the story of years of work that eventually converged on a correct answer, but the second story is far more representative of how science actually progresses.",
    "A city can be understood by the way it handles pedestrian traffic at rush hour. Some cities have worked out the choreography over generations — people walking on the correct side of the pavement, yielding without thinking, reading the flow of the crowd and slipping into it without disruption. In others, you feel the infrastructure being continuously renegotiated with every step, each person making individual decisions that do not cohere into anything systemic.",
    "My mother had a habit of saving things that other people would throw away: rubber bands, paper bags from the grocery store, the good side of used wrapping paper. I found this mildly embarrassing as a child and came to understand it as an adult: she had grown up during a period of genuine scarcity, and the habits formed then never fully dissolved even after the circumstances that made them necessary had passed.",
    "The mathematics of compound interest becomes intuitive only when you work through enough examples that the exponential curve stops feeling like a trick. The difficulty is that human intuition is built for linear processes — for distances walked, for hours worked, for goods counted — and the geometry of exponential growth operates by different rules that the unexercised mind consistently underestimates.",
    "The monastery was built on a promontory that dropped sharply on three sides into the sea. In clear weather you could see the distant smudge of the mainland; in fog, the building seemed to float in gray air with no connection to anything beyond its walls. The monks who had chosen to live there had presumably wanted exactly this sensation of removal, though the buildings themselves were not ascetic — the library was large, the refectory well-appointed, the gardens productive.",
    "Professional athletes sometimes describe a state they call being in the zone, in which the game slows, decision-making becomes effortless, and performance exceeds what can be consciously planned. Psychologists call this flow, and its characteristics are well-documented: full absorption in the task, loss of self-consciousness, a distorted sense of time, and a feeling of intrinsic reward that does not depend on the outcome. What remains poorly understood is how to reliably enter and sustain it.",
    "The first time I ate a meal I had grown myself — tomatoes, basil, and zucchini from a small plot in my backyard — the taste was indistinguishable from store-bought produce. This surprised me, because I had expected some transformation, some redemptive flavor that would justify the effort. What I got instead was the satisfaction of the process itself, which turned out to be its own reward and which, over time, I came to value more than I had anticipated.",
    "The post-war reconstruction of European cities created urban environments that were more rational and less legible than what they replaced. The old city centers that had grown incrementally over centuries were replaced in some cases by housing blocks designed according to modernist principles: light, air, and efficient organization. These projects succeeded on their own terms while failing on terms that their architects had not considered: the accumulation of social texture that occurs when people have lived side by side for generations.",
    "The relationship between exercise and mood is well established but difficult to motivate in the abstract. People who do not currently exercise rarely experience the contrast between an exercised state and an unexercised one, so the promised benefit has no emotional reality. It is an argument made in the wrong register: the evidence is empirical, but the barrier to action is not a lack of evidence but a lack of felt experience of the thing being promised.",
    "Salt has preserved food for so long that the history of its trade is, in some periods, almost indistinguishable from the history of commerce itself. The great salt routes of the ancient world — through the Sahara, along the Baltic coast, across the Alps — shaped political geography as surely as any military conquest, creating wealth for those who controlled the deposits and supply chains, and making possible the transport of perishable goods across distances that would otherwise have been impossible.",
    "The design of early video games was constrained by hardware limitations that forced designers to make aesthetic decisions they could not have anticipated valuing. The pixelated graphics, the simple color palettes, the repetitive sound effects — these were workarounds for the limited memory and processing power of the hardware of the time. Decades later, some of those constraints have become aesthetic choices in their own right, as designers deliberately recreate the look and feel of early games in new work.",
    "Migratory birds navigate using a combination of star patterns, magnetic field detection, and landscape memory so integrated that ornithologists are still working out the relative contribution of each mechanism. Some species can return to the same nesting site after a journey of thousands of miles with a precision that baffles any simple explanation. The navigation system is partly innate and partly learned, calibrated during the first migration and refined over subsequent years.",
    "The bridge over the gorge had been built in the 1930s and had the particular aesthetic of public infrastructure from that era: functional but not without grandeur, built to last by engineers who believed in the permanence of the things they made. Standing on it, I thought about the people who had laid the cables and poured the concrete, most of them now dead, whose work I was still using, which seemed like a form of transmission across time that was rarely acknowledged as such.",
]

# ---------------------------------------------------------------------------
# AI-generated test samples (author-constructed in AI style)
# Labeled as AI-generated for ground truth purposes
# ---------------------------------------------------------------------------
AI_TEST_SAMPLES = [
    "In today's rapidly evolving digital landscape, it is important to note that leveraging the transformative power of artificial intelligence represents a pivotal opportunity for organizations seeking to unlock unprecedented value. By delving into the multifaceted dimensions of machine learning and data analytics, forward-thinking enterprises can harness the power of cutting-edge algorithms to drive groundbreaking innovation and navigate the complexities of an ever-shifting global marketplace.",
    "The realm of modern biotechnology boasts numerous commendable advancements that underscore the remarkable synergies between scientific innovation and medical progress. It is worth noting that these meticulous developments have seamlessly transformed the healthcare sector, enabling holistic solutions to some of the most nuanced challenges facing humanity today. The tapestry of genomic research, in particular, stands as a testament to the boundless potential of interdisciplinary collaboration.",
    "Artificial intelligence represents a beacon of transformative potential in the contemporary technological paradigm. It is paramount that organizations adopt a comprehensive and robust framework for integrating these state-of-the-art solutions into their existing workflows. The multifaceted nature of AI implementation requires meticulous attention to both the technical intricacies and the broader ethical considerations that underpin its responsible deployment at scale.",
    "The vibrant ecosystem of the global supply chain is undergoing a comprehensive transformation, driven by the seamless integration of blockchain technology and advanced predictive analytics. It is crucial to note that these groundbreaking innovations are reshaping the foundational pillars of international commerce, enabling unprecedented levels of transparency, efficiency, and scalability. Organizations that proactively embrace this paradigm shift will be well-positioned to thrive in an increasingly competitive environment.",
    "In the realm of sustainable development, it is important to note that the synergy between environmental stewardship and economic innovation is both pivotal and transformative. By leveraging cutting-edge renewable energy solutions and delving into the intricate complexities of circular economy frameworks, forward-thinking nations can navigate the multifaceted challenges of climate change while fostering robust economic growth that is both inclusive and commensurate with the needs of future generations.",
    "The educational landscape is undergoing a revolutionary transformation, underpinned by the seamless integration of digital technologies and personalized learning methodologies. It is paramount to recognize that these holistic innovations are not merely commendable enhancements to existing curricula but rather a testament to the boundless potential of human ingenuity in adapting to the rapidly evolving demands of the twenty-first century knowledge economy.",
    "Navigating the complexities of modern geopolitical dynamics requires a nuanced understanding of the multifaceted factors that shape international relations. It is important to note that the pivotal role of multilateral institutions in fostering dialogue and promoting collaborative frameworks cannot be overstated. The tapestry of global diplomacy is woven from innumerable threads of historical precedent, cultural understanding, and strategic interest that must be meticulously balanced.",
    "The healthcare sector stands at a transformative crossroads, where cutting-edge innovations in genomics, artificial intelligence, and precision medicine are converging to unlock unprecedented possibilities for patient care. It is worth noting that this groundbreaking integration of interdisciplinary expertise represents a testament to the boundless potential of human ingenuity. Organizations must leverage these state-of-the-art advancements to foster holistic, patient-centered approaches that are both scalable and sustainable.",
    "The intersection of art and technology has given rise to a vibrant and multifaceted creative ecosystem that boasts remarkable innovation and unprecedented potential. It is important to note that these seamless integrations of algorithmic creativity and human artistic vision are reshaping the very foundations of cultural production. The transformative power of generative art, in particular, underscores the nuanced relationship between human expression and machine intelligence.",
    "In today's dynamic business environment, it is paramount that leaders embrace a comprehensive and holistic approach to organizational resilience. By delving into the intricacies of change management and leveraging cutting-edge frameworks for strategic innovation, enterprises can navigate the complexities of disruption with agility and confidence. This groundbreaking approach underscores the pivotal importance of fostering a culture of continuous learning and adaptation.",
    "The realm of quantum computing represents a beacon of transformative potential for fields ranging from cryptography to drug discovery. It is important to note that the seamless integration of quantum algorithms with classical computational frameworks will be pivotal in unlocking the full, unprecedented capabilities of this emerging technology. Organizations must adopt a meticulous and holistic strategy for quantum readiness to remain competitive in this rapidly evolving landscape.",
    "Modern urban planning is increasingly focused on creating vibrant, holistic communities that seamlessly integrate green spaces, sustainable infrastructure, and cutting-edge smart city technologies. It is paramount to recognize that these transformative approaches to urban development represent a testament to the innovative capacity of contemporary architecture and engineering. The multifaceted challenges of urbanization require nuanced, comprehensive solutions that balance the needs of diverse populations.",
    "The financial services industry is experiencing a groundbreaking transformation, driven by the seamless convergence of fintech innovation and traditional banking paradigms. It is important to note that leveraging cutting-edge blockchain technology and artificial intelligence is pivotal for institutions seeking to navigate the complexities of regulatory compliance while fostering unprecedented customer value. This holistic approach underscores the transformative potential of digital disruption.",
    "Delving into the intricacies of climate science reveals a multifaceted tapestry of interconnected systems whose complexities underscore the paramount importance of comprehensive, evidence-based policy frameworks. It is crucial to note that navigating the challenges of global warming requires a holistic integration of cutting-edge renewable technologies, robust international cooperation, and meticulous attention to the nuanced socioeconomic dimensions of the energy transition.",
    "The realm of e-commerce has witnessed a transformative evolution, driven by the seamless integration of artificial intelligence, personalized recommendations, and state-of-the-art logistics infrastructure. It is important to note that these groundbreaking innovations are reshaping consumer expectations and creating unprecedented opportunities for businesses to deliver holistic, frictionless shopping experiences at scale. Organizations that leverage these cutting-edge capabilities will be well-positioned for sustainable growth.",
    "In the rapidly evolving landscape of cybersecurity, it is paramount that organizations adopt a comprehensive and robust approach to threat management. By leveraging cutting-edge AI-driven security frameworks and delving into the multifaceted nuances of emerging attack vectors, enterprises can foster unprecedented levels of resilience and ensure the seamless protection of their digital assets. This holistic strategy underscores the pivotal role of proactive security postures.",
    "The tapestry of modern neuroscience boasts commendable advancements that are reshaping our understanding of the intricate relationship between brain function and human behavior. It is important to note that these groundbreaking discoveries are not merely academic in nature but represent a transformative beacon of hope for individuals affected by neurological conditions. The seamless integration of computational modeling and empirical research underscores the vibrant interdisciplinary nature of this field.",
    "Navigating the complexities of global talent management in the twenty-first century requires a holistic and nuanced approach that goes beyond traditional human resources paradigms. It is crucial to note that leveraging cutting-edge analytics and embracing transformative cultural frameworks are pivotal to attracting, retaining, and developing the diverse talent ecosystems that drive organizational excellence. This comprehensive strategy represents a testament to the evolving nature of leadership.",
    "The agricultural sector is undergoing a groundbreaking transformation, underpinned by the seamless integration of precision farming technologies and data-driven decision-making frameworks. It is important to note that these holistic innovations are pivotal in addressing the multifaceted challenges of food security and environmental sustainability. By leveraging state-of-the-art sensors, satellite imagery, and machine learning algorithms, farmers can unlock unprecedented levels of efficiency.",
    "In the realm of telecommunications, the advent of fifth-generation wireless technology represents a transformative and pivotal milestone in the evolution of global connectivity. It is important to note that the seamless deployment of this cutting-edge infrastructure will unlock unprecedented capabilities in areas ranging from autonomous vehicles to telemedicine, fundamentally reshaping the tapestry of human interaction and economic activity in the decades to come.",
]

# ---------------------------------------------------------------------------
# Edge case inputs
# ---------------------------------------------------------------------------
EDGE_CASES = [
    {
        "label": "Under 50 words",
        "text": "The sun rose over the mountains. Birds began to sing in the trees. A light wind moved through the grass, and the air smelled of damp earth.",
    },
    {
        "label": "Half human, half AI (spliced)",
        "text": (
            "My uncle repaired watches for thirty years in a shop no wider than a hallway. "
            "He could disassemble a mechanical movement in minutes and reassemble it without notes. "
            "In today's rapidly evolving landscape, it is important to note that leveraging "
            "cutting-edge artificial intelligence is pivotal to driving transformative outcomes. "
            "Organizations must delve into the multifaceted synergies to harness the power of "
            "data-driven insights and navigate the complexities of global markets at scale."
        ),
    },
    {
        "label": "AI text lightly hand-edited",
        "text": (
            "In a changing digital world, it is important to note that using cutting-edge "
            "artificial intelligence is pivotal for organizations that want to unlock new value. "
            "By looking closely at the many dimensions of machine learning and data analysis, "
            "companies can harness these powerful algorithms to drive innovation and navigate "
            "a shifting global marketplace with more confidence and speed than before."
        ),
    },
]


def run_validation():
    """Run the labeled test set through the pipeline and compute accuracy metrics."""
    from sklearn.metrics import roc_auc_score, f1_score, confusion_matrix
    import numpy as np

    print("Phase 1.8 Validation — Running full pipeline on labeled test set...")
    print(f"  Human samples: {len(HUMAN_TEST_SAMPLES)}")
    print(f"  AI samples: {len(AI_TEST_SAMPLES)}")
    print()

    y_true = []
    y_scores = []
    y_pred = []
    errors = []

    all_samples = (
        [(t, 0) for t in HUMAN_TEST_SAMPLES] +
        [(t, 1) for t in AI_TEST_SAMPLES]
    )

    for i, (text, label) in enumerate(all_samples):
        kind = "HUMAN" if label == 0 else "AI"
        print(f"  [{i+1}/{len(all_samples)}] Scoring {kind} sample...")
        try:
            result = analyze_text(text)
            score = result["text_score"]
            y_true.append(label)
            y_scores.append(score)
            y_pred.append(1 if score >= 50 else 0)
            print(f"    text_score={score:.1f}  (label={label}, pred={y_pred[-1]})")
        except Exception as e:
            print(f"    ERROR: {e}")
            errors.append((i, kind, str(e)))

    print()
    print("=== Metrics ===")

    y_true = np.array(y_true)
    y_scores = np.array(y_scores)
    y_pred = np.array(y_pred)

    try:
        auc = roc_auc_score(y_true, y_scores)
        print(f"ROC-AUC: {auc:.4f}")
    except Exception as e:
        print(f"ROC-AUC: ERROR — {e}")
        auc = None

    try:
        f1 = f1_score(y_true, y_pred)
        print(f"F1-score (threshold=50): {f1:.4f}")
    except Exception as e:
        print(f"F1-score: ERROR — {e}")
        f1 = None

    try:
        cm = confusion_matrix(y_true, y_pred)
        print(f"Confusion matrix (threshold=50):")
        print(f"  TN={cm[0,0]}  FP={cm[0,1]}")
        print(f"  FN={cm[1,0]}  TP={cm[1,1]}")
    except Exception as e:
        print(f"Confusion matrix: ERROR — {e}")
        cm = None

    # ---- Edge cases ----
    print()
    print("=== Edge Cases ===")
    edge_results = []
    for ec in EDGE_CASES:
        print(f"\nEdge case: {ec['label']}")
        try:
            result = analyze_text(ec["text"])
            print(f"  text_score={result['text_score']:.1f}")
            print(f"  stability_flag={result['stability_flag']}")
            print(f"  curvature_raw={result['signals']['curvature_raw']}")
            print(f"  burstiness_raw={result['signals']['burstiness_raw']}")
            print(f"  cliche_density_pct={result['signals']['cliche_density_pct']:.2f}")
            print(f"  entropy={result['signals']['entropy']:.3f}")
            edge_results.append({"label": ec["label"], "result": result})
        except Exception as e:
            print(f"  ERROR: {type(e).__name__}: {e}")
            edge_results.append({"label": ec["label"], "error": str(e)})

    # ---- Save results to markdown ----
    output_path = Path(__file__).parent / "results_phase_1_8.md"
    _save_results_md(
        output_path, y_true, y_scores, y_pred, auc, f1, cm, edge_results, errors
    )
    print(f"\nResults saved to {output_path}")
    return auc, f1, cm


def _save_results_md(path, y_true, y_scores, y_pred, auc, f1, cm, edge_results, errors):
    """Save validation results to a markdown file."""
    import numpy as np

    lines = [
        "# Phase 1.8 Validation Results",
        "",
        "## Test Set Composition",
        f"- Human samples: {int((y_true == 0).sum())} paragraphs (author-verified human text)",
        f"- AI samples: {int((y_true == 1).sum())} paragraphs (author-constructed AI-style text)",
        f"- Total: {len(y_true)} samples",
        "",
        "## Calibration Source",
        "See `calibration/baseline_stats.json` for the baseline distribution used.",
        "",
        "## Performance Metrics (threshold = 50)",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| ROC-AUC | {auc:.4f if auc is not None else 'ERROR'} |",
        f"| F1-score | {f1:.4f if f1 is not None else 'ERROR'} |",
        "",
        "## Confusion Matrix (threshold = 50)",
        "",
    ]

    if cm is not None:
        lines += [
            "| | Predicted Human | Predicted AI |",
            "|---|---|---|",
            f"| **Actually Human** | TN={cm[0,0]} | FP={cm[0,1]} |",
            f"| **Actually AI** | FN={cm[1,0]} | TP={cm[1,1]} |",
        ]
    else:
        lines.append("_Confusion matrix could not be computed._")

    lines += [
        "",
        "## Per-Sample Scores",
        "",
        "| # | Label | Score | Prediction | Correct |",
        "|---|-------|-------|-----------|---------|",
    ]
    for i, (label, score, pred) in enumerate(zip(y_true, y_scores, y_pred)):
        kind = "Human" if label == 0 else "AI"
        correct = "✅" if pred == label else "❌"
        lines.append(f"| {i+1} | {kind} | {score:.1f} | {'AI' if pred == 1 else 'Human'} | {correct} |")

    lines += [
        "",
        "## Edge Case Results",
        "",
    ]
    for er in edge_results:
        lines.append(f"### {er['label']}")
        if "error" in er:
            lines.append(f"- **Error**: {er['error']}")
        else:
            r = er["result"]
            lines += [
                f"- text_score: {r['text_score']:.1f}",
                f"- stability_flag: {r['stability_flag']}",
                f"- curvature_raw: {r['signals']['curvature_raw']}",
                f"- burstiness_raw: {r['signals']['burstiness_raw']}",
                f"- cliche_density_pct: {r['signals']['cliche_density_pct']:.2f}%",
                f"- entropy: {r['signals']['entropy']:.3f} bits",
            ]
        lines.append("")

    lines += [
        "## Errors",
        f"- {len(errors)} samples failed to score" if errors else "- No errors.",
        "",
        "## Known Limitations",
        "- distilgpt2 curvature signal shows poor discrimination (see Phase 1.2 report).",
        "- Calibration baseline uses Wikipedia/embedded corpus, not HC3.",
        "- AI test samples are author-constructed, not drawn from a real LLM output corpus.",
        "- Results should be treated as indicative, not benchmarked against published systems.",
    ]

    path.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    try:
        import sklearn
        import numpy
    except ImportError:
        print("scikit-learn and numpy required for Phase 1.8. Installing...")
        import subprocess
        subprocess.run([sys.executable, "-m", "pip", "install", "scikit-learn", "numpy"], check=True)

    run_validation()
